# Generated by Django 4.0.1 on 2022-01-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=200, null=True)),
                ('Depass', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
