# Generated by Django 4.0.1 on 2022-01-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semail', models.EmailField(max_length=200, null=True)),
                ('Spass', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
