# Generated by Django 4.0.1 on 2022-01-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineApp', '0002_accstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aname', models.CharField(max_length=200, null=True)),
                ('Alast', models.CharField(max_length=200, null=True)),
                ('Amail', models.EmailField(max_length=200, null=True)),
                ('Asid', models.CharField(max_length=200, null=True)),
                ('Acourse', models.CharField(max_length=200, null=True)),
                ('Ayg', models.CharField(max_length=200, null=True)),
                ('Adate', models.CharField(max_length=200, null=True)),
                ('Adep', models.CharField(max_length=200, null=True)),
                ('Apurp', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuardianBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ggname', models.CharField(max_length=200, null=True)),
                ('Gname', models.CharField(max_length=200, null=True)),
                ('Glast', models.CharField(max_length=200, null=True)),
                ('Gmail', models.EmailField(max_length=200, null=True)),
                ('Gsid', models.CharField(max_length=200, null=True)),
                ('Gcourse', models.CharField(max_length=200, null=True)),
                ('Gdate', models.CharField(max_length=200, null=True)),
                ('Gdep', models.CharField(max_length=200, null=True)),
                ('Gpurp', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=200, null=True)),
                ('Slast', models.CharField(max_length=200, null=True)),
                ('Smail', models.EmailField(max_length=200, null=True)),
                ('Ssid', models.CharField(max_length=200, null=True)),
                ('Scourse', models.CharField(max_length=200, null=True)),
                ('Syear', models.CharField(max_length=200, null=True)),
                ('Sdate', models.CharField(max_length=200, null=True)),
                ('Sdep', models.CharField(max_length=200, null=True)),
                ('Spurp', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
