# Generated by Django 4.0.1 on 2022-01-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineApp', '0003_alumnibook_guardianbook_studentbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnibook',
            name='Asid',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='guardianbook',
            name='Gsid',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='studentbook',
            name='Ssid',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
