# Generated by Django 4.0.1 on 2022-01-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineApp', '0004_alter_alumnibook_asid_alter_guardianbook_gsid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ggname', models.CharField(max_length=200, null=True)),
                ('Sname', models.CharField(max_length=200, null=True)),
                ('Slast', models.CharField(max_length=200, null=True)),
                ('Smail', models.EmailField(max_length=200, null=True)),
                ('Ssid', models.CharField(max_length=12, null=True)),
                ('Scourse', models.CharField(max_length=200, null=True)),
                ('Syear', models.CharField(max_length=200, null=True)),
                ('Sdate', models.CharField(max_length=200, null=True)),
                ('Sdep', models.CharField(max_length=200, null=True)),
                ('Spurp', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='alumnibook',
            name='stats1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentbook',
            name='Ggname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
