# Generated by Django 4.0.1 on 2022-01-28 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineApp', '0007_delete_book_studentbook_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbook',
            name='Ggname',
        ),
        migrations.RemoveField(
            model_name='studentbook',
            name='status',
        ),
    ]
