# Generated by Django 4.0.1 on 2022-01-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineApp', '0008_remove_studentbook_ggname_remove_studentbook_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnibook',
            old_name='stats1',
            new_name='status',
        ),
        migrations.AddField(
            model_name='guardianbook',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentbook',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
