# Generated by Django 4.0.1 on 2022-01-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineApp', '0009_rename_stats1_alumnibook_status_guardianbook_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnibook',
            name='status',
            field=models.CharField(default='Inbox', max_length=200),
        ),
    ]
