# Generated by Django 4.0.1 on 2022-01-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineApp', '0010_alter_alumnibook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianbook',
            name='status',
            field=models.CharField(default='Inbox', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentbook',
            name='status',
            field=models.CharField(default='Inbox', max_length=200),
        ),
    ]
